### ISSUE TITLE
Smarty 4 error

### ISSUE THREAD

**Issue by netzih** [Skvare/com.skvare.mosaicomigration#1]
The extension is throwing an error which seems to be triggered by some template which is not smarty4 compatible,

When trying to access the settings for the extension I get the following error
`Unable to load template 'file:CRM/Mosaicomigration/Form/Migration.tpl' in 'file:CRM/Form/default.tpl`

When checking the logs I see 
`2024-08-30 03:27:04+0100  [error] 
$Fatal Error Details = array:3 [
  "message" => "Unable to load template 'file:CRM/Mosaicomigration/Form/Migration.tpl' in 'file:CRM/Form/default.tpl'"
  "code" => null
  "exception" => SmartyException {#7761
    #message: "Unable to load template 'file:CRM/Mosaicomigration/Form/Migration.tpl' in 'file:CRM/Form/default.tpl'"
    #code: 0
    #file: "/httpdocs/wp-content/plugins/civicrm/civicrm/packages/smarty4/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php"
    #line: 196
    trace: {
      /httpdocs/wp-content/plugins/civicrm/civicrm/packages/smarty4/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php:196 { …}
      /httpdocs/wp-content/plugins/civicrm/civicrm/packages/smarty4/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php:386 { …}
     /httpdocs/wp-content/uploads/civicrm/templates_c/en_US/1d/cd/18/1dcd188a338ccf775d851186f3f8356d0aec7b57_0.file.default.tpl.php:53 {
        content_66d00c0e50d9c3_02489593(Smarty_Internal_Template $_smarty_tpl)
        › 
        ›     <?php $_smarty_tpl->_subTemplateRender($_smarty_tpl->tpl_vars['tplFile']->value, $_smarty_tpl->cache_id, $_smarty_tpl->compile_id, 0, $_smarty_tpl->cache_lifetime, array(), 0, true);
        › ?>
      }
     /httpdocs/wp-content/plugins/civicrm/civicrm/packages/smarty4/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php:123 { …}
      /httpdocs/wp-content/plugins/civicrm/civicrm/packages/smarty4/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php:114 { …}
      /httpdocs/wp-content/plugins/civicrm/civicrm/packages/smarty4/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php:217 { …}
      /httpdocs/wp-content/plugins/civicrm/civicrm/packages/smarty4/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php:386 { …}
     /httpdocs/wp-content/uploads/civicrm/templates_c/en_US/a5/c9/e6/a5c9e6731c19f966d5a2c93bf554707195483931_0.file.CMSPrint.tpl.php:100 { …}
      /httpdocs/wp-content/plugins/civicrm/civicrm/packages/smarty4/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php:123 { …}
      /httpdocs/wp-content/plugins/civicrm/civicrm/packages/smarty4/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php:114 { …}
     /httpdocs/wp-content/plugins/civicrm/civicrm/packages/smarty4/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php:217 { …}
     /httpdocs/wp-content/plugins/civicrm/civicrm/packages/smarty4/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php:386 { …}
     /httpdocs/wp-content/uploads/civicrm/templates_c/en_US/0b/2a/88/0b2a883467076627eab54600ec1f9303a49f2fb1_0.file.wordpress.tpl.php:31 { …}
      /httpdocs/wp-content/plugins/civicrm/civicrm/packages/smarty4/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php:123 { …}
     /httpdocs/wp-content/plugins/civicrm/civicrm/packages/smarty4/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php:114 { …}
      /httpdocs/wp-content/plugins/civicrm/civicrm/packages/smarty4/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php:217 { …}
      /httpdocs/wp-content/plugins/civicrm/civicrm/packages/smarty4/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php:238 { …}
     /httpdocs/wp-content/plugins/civicrm/civicrm/packages/smarty4/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php:116 { …}
     /httpdocs/wp-content/plugins/civicrm/civicrm/CRM/Core/QuickForm/Action/Display.php:117 { …}
      /httpdocs/wp-content/plugins/civicrm/civicrm/CRM/Core/QuickForm/Action/Display.php:83 { …}
     /httpdocs/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/Controller.php:203 { …}
     /httpdocs/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/Page.php:103 { …}
    /httpdocs/wp-content/plugins/civicrm/civicrm/CRM/Core/Controller.php:355 { …}
    /httpdocs/wp-content/plugins/civicrm/civicrm/CRM/Utils/Wrapper.php:98 { …}
     /wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php:296 { …}
      /wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php:69 { …}
      /wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php:36 { …}
      /httpdocs/wp-content/plugins/civicrm/civicrm.php:1231 { …}
      /httpdocs/wp-includes/class-wp-hook.php:324 { …}
      /httpdocs/wp-includes/class-wp-hook.php:348 { …}
     /httpdocs/wp-includes/plugin.php:517 { …}
      /httpdocs/wp-admin/admin.php:259 { …}
    }
  }
]

2024-08-30 03:27:04+0100  [debug] $backTrace = #0 /httpdocs/wp-content/plugins/civicrm/civicrm/CRM/Core/Error.php(443): CRM_Core_Error::backtrace("backTrace", TRUE)
#1 /httpdocs/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(39): CRM_Core_Error::handleUnhandledException(Object(SmartyException))
#2 /httpdocs/wp-content/plugins/civicrm/civicrm.php(1231): CRM_Core_Invoke::invoke((Array:2))
#3 /httpdocs/wp-includes/class-wp-hook.php(324): CiviCRM_For_WordPress->invoke("")
#4 /httpdocs/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters("", (Array:1))
#5 /httpdocs/wp-includes/plugin.php(517): WP_Hook->do_action((Array:1))
#6 /httpdocs/wp-admin/admin.php(259): do_action("toplevel_page_CiviCRM")
#7 {main}`

**Comment by sunilpawar** [comment]
Released new tag with fix https://github.com/Skvare/com.skvare.mosaicomigration/releases/tag/1.4

soon it would be availble on [https://civicrm.org](https://civicrm.org/extensions/mosaico-and-mailing-configuration-changes ) too.
